name: Run Tests with Anvil

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start Anvil
        uses: ./

      - name: Show Anvil log if startup fails
        if: failure()
        run: cat anvil.log

      - name: Run tests
        run: |
          npm install
          npm test
